name: List directory (debugging)

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: ls
      run: |
        echo | ls .
        echo | ls ../
